/**
 * click-tracker — Supabase Edge Function click-tracking redirect.
 *
 * Runs ALONGSIDE the existing open-tracking pixel (campaign-tracker) and the
 * legacy Express click endpoint (backend/routes/trackingRoutes.js). It is the
 * endpoint that send-campaign and send-followup rewrite email links to, so
 * clicks work even when the local backend is offline:
 *
 *   GET {SUPABASE_EDGE_FUNCTION_URL}/click-tracker
 *         ?tracking_id=<uuid>&url=<encoded_original_url>
 *   (weekly welcome emails:
 *         ?source=weekly&queue_id=<uuid>&url=<encoded_original_url>)
 *
 * `tracking_id` is the unique UUID already stored on email_logs.tracking_id by
 * the senders, so it uniquely identifies the exact email_log (campaign +
 * recipient + which send: original or follow-up). It needs no Authorization
 * header (email clients / browsers open the link directly), so JWT
 * verification is disabled (see supabase/config.toml).
 *
 * WEEKLY welcome emails (source=weekly&queue_id) instead mark the
 * `weekly_email_queue` row `clicked_at = now()` on the FIRST click only —
 * additive; campaign/sequence tracking (email_logs + campaign_analytics)
 * below is unchanged.
 *
 * On a click it:
 *   1. resolves the email_log by tracking_id,
 *   2. marks clicked = true, clicked_at = now() on the FIRST click only
 *      (subsequent clicks no-op, so click counts/rates are unique-recipient
 *      and clicked_at is always the first click time),
 *   3. recomputes campaign_analytics clicked / click_rate (and re-derives
 *      delivered/opened/open_rate) from email_logs — idempotent and safe to
 *      run alongside the open pixel,
 *   4. for weekly welcome emails, sets weekly_email_queue.clicked_at,
 *   5. 302-redirects to the original URL.
 *
 * Security: only http:// and https:// destinations are accepted (a click URL
 * is generated by our own senders and the encoded destination is opened by
 * the recipient, so the redirect must never point at file://, javascript:,
 * etc.). An unknown/invalid tracking_id never blocks the redirect.
 */ import { createClient } from 'npm:@supabase/supabase-js@2';
const supabaseUrl = Deno.env.get('SUPABASE_URL');
const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || Deno.env.get('SUPABASE_ANON_KEY');
const supabase = createClient(supabaseUrl, supabaseKey);
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function log(...args) {
  console.log('[click-tracker]', ...args);
}
function isSafeDestination(value) {
  try {
    const parsed = new URL(value);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch  {
    return false;
  }
}
async function recordClick(trackingId) {
  const { data: matches, error: readError } = await supabase.from('email_logs').select('id, campaign_id, email, clicked').eq('tracking_id', trackingId).limit(1);
  if (readError) {
    log('Failed reading email_log', `code=${readError.code}`, readError.message);
    return null;
  }
  const row = matches?.[0];
  if (!row) {
    log('NO MATCH', `tracking_id=${trackingId}`);
    return null;
  }
  const clickedBefore = row.clicked === true;
  if (!clickedBefore) {
    const { error } = await supabase.from('email_logs').update({
      clicked: true,
      clicked_at: new Date().toISOString()
    }).eq('id', row.id);
    if (error) {
      log('Email Log Updated — FAILED', `code=${error.code}`, error.message);
    }
  }
  log('Email Log Updated —', `log_id=${row.id}`, `campaign_id=${row.campaign_id}`, `email=${row.email}`, `clicked before=${clickedBefore}`, 'clicked after=true', `tracking_id=${trackingId}`);
  return row.campaign_id;
}
/** Weekly queue: record the FIRST click of a weekly welcome email on its queue row. */
async function updateWeeklyQueueClick(queueId: string): Promise<void> {
  const { error } = await supabase
    .from('weekly_email_queue')
    .update({ clicked_at: new Date().toISOString() })
    .eq('id', queueId)
    .is('clicked_at', null);
  if (error) {
    log('Weekly Queue Click Updated — FAILED', `queue_id=${queueId}`, `code=${error.code}`, error.message);
    if (String(error.code).startsWith('PGRST') || /column .* does not exist/i.test(error.message ?? '')) {
      log('Hint: run migration 20260929000000_weekly_queue_tracking_columns.sql (adds weekly_email_queue.opened_at/clicked_at)');
    }
    return;
  }
  log('Weekly Queue Click Updated —', `queue_id=${queueId}`);
}
async function updateAnalytics(campaignId) {
  const { data: logs, error: logsError } = await supabase.from('email_logs').select('status, opened, clicked').eq('campaign_id', campaignId);
  if (logsError) {
    log('Analytics Updated — FAILED reading email_logs', `code=${logsError.code}`, logsError.message);
    return;
  }
  const rows = logs ?? [];
  const total = rows.length;
  const delivered = rows.filter((r)=>r.status === 'sent').length;
  const opened = rows.filter((r)=>r.opened === true).length;
  const clicked = rows.filter((r)=>r.clicked === true).length;
  const openRate = delivered > 0 ? Math.round(opened / delivered * 1000) / 10 : 0;
  const clickRate = delivered > 0 ? Math.round(clicked / delivered * 1000) / 10 : 0;
  const { data: existing } = await supabase.from('campaign_analytics').select('*').eq('campaign_id', campaignId).maybeSingle();
  const { error } = await supabase.from('campaign_analytics').upsert({
    campaign_id: campaignId,
    total_recipients: existing?.total_recipients ?? total,
    delivered,
    opened,
    clicked,
    open_rate: openRate,
    click_rate: clickRate
  }, {
    onConflict: 'campaign_id'
  });
  if (error) {
    log('Analytics Updated — FAILED', `code=${error.code}`, error.message);
    if (String(error.code) === '55000' || /cannot (update|insert into) view/i.test(error.message ?? '')) {
      log('Hint: campaign_analytics is a read-only VIEW — make it a table (see backend/email_tracking_migration.sql)');
    }
    return;
  }
  log('Analytics Updated — clicked =', clicked, 'click_rate =', clickRate);
}
Deno.serve(async (req)=>{
  const url = new URL(req.url);
  const trackingId = url.searchParams.get('tracking_id') || '';
  const destination = url.searchParams.get('url') || '';
  const source = url.searchParams.get('source');
  const queueId = url.searchParams.get('queue_id') || '';
  log('Click Requested —', url.toString());
  log('Tracking ID —', trackingId || '(missing)');
  log('Destination —', destination ? destination.slice(0, 200) : '(missing)');
  if (!destination || !isSafeDestination(destination)) {
    log('Skipped — destination missing or not http(s)');
    return new Response('Bad Request: missing or unsafe url parameter', {
      status: 400,
      headers: {
        'Content-Type': 'text/plain',
        'Cache-Control': 'no-store'
      }
    });
  }
  // Weekly welcome emails: record the FIRST click on the queue row itself.
  // Additive — the email_logs tracking path below is unchanged.
  if (source === 'weekly' && queueId) {
    await updateWeeklyQueueClick(queueId);
  }
  if (UUID_RE.test(trackingId)) {
    const campaignId = await recordClick(trackingId);
    if (campaignId) await updateAnalytics(campaignId);
  } else {
    log('Skipped recording — tracking_id missing or not a UUID');
  }
  // Always reach the destination, even if tracking lookup failed.
  return new Response(null, {
    status: 302,
    headers: {
      Location: destination,
      'Cache-Control': 'no-store, no-cache, must-revalidate, private'
    }
  });
});
